{
  "openapi": "3.0.2",
  "info": {
    "title": "API Spec for Repository Scientific API",
    "version": "1.0.0",
    "description": "My final project for accomplish my study at Politeknik Negeri Cilacap."
  },
  "tags": [
    {
      "name": "Category",
      "description": "API Spec for Category"
    },
    {
      "name": "Collection",
      "description": "API Spec for Collection"
    },
    {
      "name": "Role",
      "description": "API Spec for Role"
    },
    {
      "name": "Study Program",
      "description": "API Spec for Study Program"
    }
  ],
  "servers": [{ "url": "http://localhost:8080/api/v1", "description": "Local environment" }],
  "paths": {
    "/categories": {
      "post": {
        "tags": ["Category"],
        "summary": "Create category",
        "description": "Create category",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Programming"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success create category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "code": 201,
                  "status": "success",
                  "message": "CREATED"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Category"],
        "summary": "List all categories",
        "description": "List all categories",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "programming"
            },
            "name": "keyword",
            "in": "query"
          },
          {
            "schema": {
              "type": "number",
              "example": 10
            },
            "required": true,
            "name": "limit",
            "in": "query"
          },
          {
            "schema": {
              "type": "number",
              "example": 1
            },
            "required": true,
            "name": "page",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all categories",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Category"
                      }
                    },
                    "pagination": {
                      "$ref": "#/components/schemas/Pagination"
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "OK",
                  "data": [
                    {
                      "id": "850c3915-16ea-4e2f-b068-5e25108ff681",
                      "name": "Multimedia",
                      "created_at": "2022-12-31T23:04:17+07:00",
                      "updated_at": "2022-12-31T23:04:17+07:00"
                    },
                    {
                      "id": "eb2b5257-0380-4afc-9ab7-c41915f0672e",
                      "name": "Networking",
                      "created_at": "2022-12-31T23:15:43+07:00",
                      "updated_at": "2022-12-31T23:20:24+07:00"
                    }
                  ],
                  "pagination": {
                    "page": 1,
                    "limit": 10,
                    "total_rows": 2,
                    "total_pages": 1
                  }
                }
              }
            }
          }
        }
      }
    },
    "/categories/{categoryId}": {
      "put": {
        "tags": ["Category"],
        "summary": "Update category",
        "description": "Update category",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "required": true,
            "name": "categoryId",
            "in": "path"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Programming"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "OK"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Category"],
        "description": "Get category by id category",
        "summary": "Get category by id",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "required": true,
            "name": "categoryId",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get category by id category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/Category"
                    }
                  },
                  "example": {
                    "code": 200,
                    "status": "success",
                    "message": "OK",
                    "data": {
                      "id": "eb2b5257-0380-4afc-9ab7-c41915f0672e",
                      "name": "Networking",
                      "created_at": "2022-12-31T23:15:43+07:00",
                      "updated_at": "2022-12-31T23:20:24+07:00"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/collections": {
      "post": {
        "tags": ["Collection"],
        "description": "Create collection",
        "summary": "Crete collection",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "Laporan Tugas Akhir"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success create collection",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "code": 201,
                    "status": "success",
                    "message": "CREATED"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Collection"],
        "description": "List all collections",
        "summary": "List all collections",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "name": "keyword",
            "in": "query"
          },
          {
            "schema": {
              "type": "number",
              "example": 10
            },
            "required": true,
            "name": "limit",
            "in": "query"
          },
          {
            "schema": {
              "type": "number",
              "example": 1
            },
            "required": true,
            "name": "page",
            "in": "query"
          }
        ],
        "responses": {
          "201": {
            "description": "Success get all collections",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Collection"
                      }
                    },
                    "pagination": {
                      "$ref": "#/components/schemas/Pagination"
                    }
                  },
                  "example": {
                    "code": 201,
                    "status": "success",
                    "message": "OK",
                    "data": [
                      {
                        "id": "849229b7-b224-4391-8cf9-9f01122e3667",
                        "name": "Laporan Tugas Akhir",
                        "created_at": "2023-01-01T15:44:03+07:00",
                        "updated_at": "2023-01-01T15:46:18+07:00"
                      },
                      {
                        "id": "b6467238-590c-4bd6-b468-054bfe10de59",
                        "name": "Laporan Hasil Magang",
                        "created_at": "2023-01-01T15:43:51+07:00",
                        "updated_at": "2023-01-01T15:43:51+07:00"
                      }
                    ],
                    "pagination": {
                      "page": 1,
                      "limit": 10,
                      "total_rows": 2,
                      "total_pages": 1
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/collections/{collectionId}": {
      "put": {
        "tags": ["Collection"],
        "summary": "Update collection",
        "description": "Update collection",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "required": true,
            "name": "collectionId",
            "in": "path"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Laporan Hasil Magang"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update collection",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "code": 200,
                    "status": "success",
                    "message": "OK"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Collection"],
        "description": "Get collection by id collection",
        "summary": "Get collection by id",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "required": true,
            "name": "collectionId",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get collection by id collection",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/Collection"
                    }
                  },
                  "example": {
                    "code": 200,
                    "status": "success",
                    "message": "OK",
                    "data": {
                      "id": "849229b7-b224-4391-8cf9-9f01122e3667",
                      "name": "Laporan Tugas Akhir",
                      "created_at": "2023-01-01T15:44:03+07:00",
                      "updated_at": "2023-01-01T15:46:18+07:00"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/roles": {
      "post": {
        "tags": ["Role"],
        "description": "Create role",
        "summary": "Create role",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "role": {
                    "type": "string"
                  },
                  "visibility": {
                    "type": "string"
                  }
                },
                "example": {
                  "role": "Mahasiswa",
                  "visibility": "pemustaka"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success create role",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "code": 201,
                    "status": "success",
                    "message": "CREATED"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Role"],
        "summary": "List all roles",
        "description": "List all roles",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": ""
            },
            "name": "visibility",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all roles",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Role"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "OK",
                  "data": [
                    {
                      "id": "fade66ce-4290-4b66-bf07-37205aea3ce7",
                      "role": "Dosen",
                      "visibility": "pemustaka",
                      "created_at": "2023-01-02T05:54:10+07:00",
                      "updated_at": "2023-01-02T05:55:03+07:00"
                    },
                    {
                      "id": "c0e4b0f2-6338-40df-be43-9173bf48bcd1",
                      "role": "Mahasiswa",
                      "visibility": "pemustaka",
                      "created_at": "2023-01-02T05:54:02+07:00",
                      "updated_at": "2023-01-02T05:54:02+07:00"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/roles/{roleId}": {
      "put": {
        "tags": ["Role"],
        "summary": "Update role",
        "description": "Update role",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "required": true,
            "name": "roleId",
            "in": "path"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "role": {
                    "type": "string"
                  },
                  "visibility": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "role": "Dosen",
                "visibility": "pemustaka"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update role",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "code": 200,
                    "status": "success",
                    "message": "OK"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Role"],
        "description": "Get role by id role",
        "summary": "Get role by id",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "required": true,
            "name": "roleId",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get role by id role",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/Role"
                    }
                  },
                  "example": {
                    "code": 200,
                    "status": "success",
                    "message": "OK",
                    "data": {
                      "id": "c0e4b0f2-6338-40df-be43-9173bf48bcd1",
                      "role": "Mahasiswa",
                      "visibility": "pemustaka",
                      "created_at": "2023-01-02T05:54:02+07:00",
                      "updated_at": "2023-01-02T05:54:02+07:00"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/study-programs": {
      "post": {
        "tags": ["Study Program"],
        "description": "Create study program",
        "summary": "Create study program",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "D3 - Teknik Informatika"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success create study program",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "code": 201,
                    "status": "success",
                    "message": "CREATED"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Study Program"],
        "summary": "List all study programs",
        "description": "List all study programs",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": ""
            },
            "name": "keyword",
            "in": "query"
          },
          {
            "schema": {
              "type": "number",
              "example": 10
            },
            "required": true,
            "name": "limit",
            "in": "query"
          },
          {
            "schema": {
              "type": "number",
              "example": 1
            },
            "required": true,
            "name": "page",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all study programs",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/StudyProgram"
                      }
                    },
                    "pagination": {
                      "$ref": "#/components/schemas/Pagination"
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "OK",
                  "data": [
                    {
                      "id": "c837de18-3c59-41df-a28b-ed96f147f710",
                      "name": "D-3 Teknik Elektronika",
                      "created_at": "2023-01-02T21:52:00+07:00",
                      "updated_at": "2023-01-02T21:54:18+07:00"
                    },
                    {
                      "id": "bdcc445e-3129-46d2-bae5-6ad490d7e5a4",
                      "name": "D-3 Teknik Informatika",
                      "created_at": "2023-01-02T21:51:53+07:00",
                      "updated_at": "2023-01-02T21:51:53+07:00"
                    }
                  ],
                  "pagination": {
                    "page": 1,
                    "limit": 10,
                    "total_rows": 2,
                    "total_pages": 1
                  }
                }
              }
            }
          }
        }
      }
    },
    "/study-programs/{studyProgramId}": {
      "put": {
        "tags": ["Study Program"],
        "summary": "Update study program",
        "description": "Update study program",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "required": true,
            "name": "studyProgramId",
            "in": "path"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "D3 - Teknik Informatika"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update study program",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "code": 200,
                    "status": "success",
                    "message": "OK"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Study Program"],
        "description": "Get study program by id study program",
        "summary": "Get study program by id",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "required": true,
            "name": "studyProgramId",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get study program by id study program",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/StudyProgram"
                    }
                  },
                  "example": {
                    "code": 200,
                    "status": "success",
                    "message": "OK",
                    "data": {
                      "id": "c837de18-3c59-41df-a28b-ed96f147f710",
                      "name": "D-3 Teknik Elektronika",
                      "created_at": "2023-01-02T21:52:00+07:00",
                      "updated_at": "2023-01-02T21:54:18+07:00"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Collection": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Role": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "visibility": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "StudyProgram": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Pagination": {
        "type": "object",
        "properties": {
          "page": {
            "type": "number"
          },
          "limit": {
            "type": "number"
          },
          "total_rows": {
            "type": "number"
          },
          "total_pages": {
            "type": "number"
          }
        }
      }
    }
  }
}
